#!/usr/bin/env node
// gen-wrapper.cjs — post-build script that generates index.js (CJS) and
// index.mjs (ESM) with the SnapdirError class and wrapped native exports.
// Called by: npm run build (after `napi build --platform --release --no-js`).

'use strict'

const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.join(__dirname, '..')

// ---------------------------------------------------------------------------
// Native loader content for index.js (CJS)
// ---------------------------------------------------------------------------

const NATIVE_LOADER_CJS = `'use strict'
/* eslint-disable */
// @ts-nocheck
// CJS entry — generated by scripts/gen-wrapper.cjs (post napi build --no-js)

const { readFileSync } = require('fs')

// ---------------------------------------------------------------------------
// SnapdirError — Error subclass with a .code property (one of the 8 stable
// error codes from snapdir-api). Thrown instead of plain napi Errors so that
// callers can: \`caught instanceof SnapdirError\` and \`err.code === 'IO_ERROR'\`.
// ---------------------------------------------------------------------------
class SnapdirError extends Error {
  constructor(code, message) {
    super(message)
    this.name = 'SnapdirError'
    this.code = code
  }
}

// Parse the "[CODE] message" prefix that lib.rs embeds in napi error messages.
function _parseNativeError(e) {
  const m = /^\\[([A-Z_]+)\\] (.*)$/s.exec(e?.message ?? '')
  if (m) {
    const err = new SnapdirError(m[1], m[2])
    err.stack = e.stack
    return err
  }
  // Not a snapdir error — re-wrap as STORE_ERROR to stay instanceof SnapdirError.
  const err = new SnapdirError('STORE_ERROR', e?.message ?? String(e))
  err.stack = e?.stack
  return err
}

// Wrap a CPU-bound async native function so its rejections become SnapdirError.
// The napi AsyncTask runs genuinely off-thread (libuv thread pool), so there is
// no need to defer the resolution — let it resolve/reject directly from the
// AsyncTask completion callback.
function _wrapAsyncCpu(fn) {
  return function (...args) {
    return fn.apply(this, args).then(
      (v) => v,
      (e) => { throw _parseNativeError(e) }
    )
  }
}

// Wrap an I/O-bound async native function (no extra delay needed).
function _wrapAsync(fn) {
  return function (...args) {
    return fn.apply(this, args).then(
      (v) => v,
      (e) => { throw _parseNativeError(e) }
    )
  }
}

// ---------------------------------------------------------------------------
// Native binding loader
// ---------------------------------------------------------------------------
let nativeBinding = null
const loadErrors = []
const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    try { musl = readFileSync('/usr/bin/ldd', 'utf-8').includes('musl') } catch {}
    if (musl === null) {
      try {
        const report = process.report?.getReport?.()
        if (report?.header?.glibcVersionRuntime) musl = false
        else if (report?.sharedObjects?.some(f => f.includes('libc.musl-') || f.includes('ld-musl-'))) musl = true
      } catch {}
    }
  }
  return musl
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try { return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH) } catch (e) { loadErrors.push(e) }
  }
  if (process.platform === 'darwin') {
    try { return require('./snapdir.darwin-universal.node') } catch (e) { loadErrors.push(e) }
    if (process.arch === 'arm64') {
      try { return require('./snapdir.darwin-arm64.node') } catch (e) { loadErrors.push(e) }
    } else if (process.arch === 'x64') {
      try { return require('./snapdir.darwin-x64.node') } catch (e) { loadErrors.push(e) }
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try { return require('./snapdir.linux-x64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./snapdir.linux-x64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try { return require('./snapdir.linux-arm64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./snapdir.linux-arm64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    }
  } else if (process.platform === 'win32' && process.arch === 'x64') {
    try { return require('./snapdir.win32-x64-msvc.node') } catch (e) { loadErrors.push(e) }
  }
  if (loadErrors.length > 0) {
    const error = new Error('Cannot find native binding.')
    error.cause = loadErrors[loadErrors.length - 1]
    throw error
  }
  throw new Error('Failed to load native binding')
}

nativeBinding = requireNative()

// ---------------------------------------------------------------------------
// Wrapped exports
//
// manifest / id / stage: CPU-bound AsyncTask (napi_queue_async_work).
//   Use _wrapAsyncCpu so rejections become SnapdirError. The AsyncTask runs
//   genuinely off-thread; no resolution deferral is needed or added.
//
// push / fetch / pull / checkout / sync / diff / verify: I/O-bound async fns.
//   Use _wrapAsync (same direct resolution + SnapdirError mapping).
// ---------------------------------------------------------------------------
module.exports = {
  SnapdirError,
  version: nativeBinding.version.bind(nativeBinding),
  idFromManifest: nativeBinding.idFromManifest.bind(nativeBinding),
  manifest: _wrapAsyncCpu(nativeBinding.manifest.bind(nativeBinding)),
  id: _wrapAsyncCpu(nativeBinding.id.bind(nativeBinding)),
  stage: _wrapAsyncCpu(nativeBinding.stage.bind(nativeBinding)),
  push: _wrapAsync(nativeBinding.push.bind(nativeBinding)),
  fetch: _wrapAsync(nativeBinding.fetch.bind(nativeBinding)),
  pull: _wrapAsync(nativeBinding.pull.bind(nativeBinding)),
  checkout: _wrapAsync(nativeBinding.checkout.bind(nativeBinding)),
  sync: _wrapAsync(nativeBinding.sync.bind(nativeBinding)),
  diff: _wrapAsync(nativeBinding.diff.bind(nativeBinding)),
  verify: _wrapAsync(nativeBinding.verify.bind(nativeBinding)),
}
`

// ---------------------------------------------------------------------------
// ESM wrapper (index.mjs) — same logic, ES module syntax
// ---------------------------------------------------------------------------
const ESM_WRAPPER = `// index.mjs — ESM entry for @snapdir/snapdir
// Generated by scripts/gen-wrapper.cjs (post napi build --no-js).
// Uses createRequire to load the CJS native binding.

import { createRequire } from 'node:module'
const _require = createRequire(import.meta.url)

// Load the CJS wrapper (which includes SnapdirError + wrapped fns).
const _cjs = _require('./index.js')

export const SnapdirError = _cjs.SnapdirError
export const version = _cjs.version
export const idFromManifest = _cjs.idFromManifest
export const manifest = _cjs.manifest
export const id = _cjs.id
export const stage = _cjs.stage
export const push = _cjs.push
export const fetch = _cjs.fetch
export const pull = _cjs.pull
export const checkout = _cjs.checkout
export const sync = _cjs.sync
export const diff = _cjs.diff
export const verify = _cjs.verify
`

// ---------------------------------------------------------------------------
// Write files
// ---------------------------------------------------------------------------
fs.writeFileSync(path.join(ROOT, 'index.js'), NATIVE_LOADER_CJS, 'utf8')
fs.writeFileSync(path.join(ROOT, 'index.mjs'), ESM_WRAPPER, 'utf8')

console.log('[gen-wrapper] Wrote index.js (CJS) and index.mjs (ESM)')

// ---------------------------------------------------------------------------
// Extend index.d.ts with missing types
// ---------------------------------------------------------------------------
const DTS_PATH = path.join(ROOT, 'index.d.ts')
let dts = fs.readFileSync(DTS_PATH, 'utf8')

// Replace DiffEntry.status from string to DiffStatus
dts = dts.replace(
  /export interface DiffEntry \{[^}]*\}/s,
  `export interface DiffEntry {
  /** Change status: one of the frozen glyphs. */
  status: DiffStatus
  /** The entry path. */
  path: string
}`
)

// napi emits `const enum PathType { File='File', Directory='Directory' }` — a
// nominal type that won't === the 'File'|'Directory' union the locked test and
// consumers expect (and which DiffStatus already uses). Convert to a string union.
dts = dts.replace(
  /export declare const enum PathType \{[^}]*\}/s,
  "export type PathType = 'File' | 'Directory'"
)

// Add the missing type aliases and SnapdirError class BEFORE the first export
const EXTRA_TYPES = `/**
 * A 64-lowercase-hex snapshot identifier string.
 *
 * Every \`id()\`/\`idFromManifest()\` call returns a value of this type.
 */
export type SnapshotId = string

/**
 * The change status of a single entry in a diff result.
 *
 * Frozen single-character glyphs: \`'A'\` (Added), \`'D'\` (Deleted),
 * \`'M'\` (Modified), \`'='\` (Unchanged).
 */
export type DiffStatus = 'A' | 'D' | 'M' | '='

/**
 * A snapdir-specific error with a stable \`.code\` string.
 *
 * \`code\` is one of the 8 frozen cross-language codes from \`snapdir-api\`:
 * IO_ERROR, HASH_MISMATCH, STORE_ERROR, IN_FLUX, CATALOG_ERROR,
 * INVALID_ID, INVALID_STORE, CONFLICT.
 */
export declare class SnapdirError extends Error {
  /** Stable SCREAMING_SNAKE_CASE error code (one of the 8 frozen codes). */
  code: string
  constructor(code: string, message: string)
}

`

// Prepend extra types after the auto-generated header comment block
dts = dts.replace(/^(\/\* auto-generated by NAPI-RS \*\/\n\/\* eslint-disable \*\/\n)/, `$1${EXTRA_TYPES}`)

// Fix: make id(), idFromManifest(), stage(), push() return Promise<SnapshotId>
// The auto-gen returns Promise<string>; since SnapshotId = string, compatible.
// We retype for developer experience:
dts = dts.replace(/: Promise<string>/g, ': Promise<SnapshotId>')

// Fix: idFromManifest return type (in case it's still 'string' after the global replace)
dts = dts.replace(
  'export declare function idFromManifest(m: Manifest): string',
  'export declare function idFromManifest(m: Manifest): SnapshotId'
)

// Fix: AsyncTask return types — napi-rs generates Promise<unknown> for Task-based fns.
// Retype to the correct concrete types:
dts = dts.replace(
  /export declare function manifest\([^)]*\): Promise<unknown>/,
  'export declare function manifest(path: string, options?: ManifestOptions): Promise<Manifest>'
)
dts = dts.replace(
  /export declare function id\([^)]*\): Promise<unknown>/,
  'export declare function id(path: string, options?: ManifestOptions): Promise<SnapshotId>'
)
dts = dts.replace(
  /export declare function stage\([^)]*\): Promise<unknown>/,
  'export declare function stage(path: string): Promise<SnapshotId>'
)

fs.writeFileSync(DTS_PATH, dts, 'utf8')
console.log('[gen-wrapper] Extended index.d.ts with SnapshotId, DiffStatus, SnapdirError')
