#!/bin/bash
# sidecars-up.sh — start minio (S3/B2/GCS-compat) + sshd (SSH/SFTP) parity sidecars.
#
# Parity network-store endpoints for Phase-36 manifest-parity harness:
#   S3/B2/GCS (S3-compat)  →  http://127.0.0.1:9000  (minio)
#   SSH / SFTP             →  127.0.0.1:2222          (sshd)
#
# Test credentials (loopback-only, non-secret):
#   MinIO root user:       snapdir-test
#   MinIO root password:   snapdir-test-secret
#   SSH user:              snapdir (current user alias via authorized_keys)
#   SSH key:               /workspace/scripts/sidecar_ssh_key (ed25519, passphrase-free)
#   SSH known_hosts:       /workspace/scripts/sidecar_known_hosts
#
# Ports (also written to sidecars.env):
#   MINIO_PORT=9000
#   SSHD_PORT=2222
#
# Idempotent: if a process is already listening on the port the script
# exits 0 without spawning a second instance.

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPTS_DIR}/sidecars.env"

# ── helpers ───────────────────────────────────────────────────────────────────
port_listening() {
    # Returns 0 (true) if something is already bound to 127.0.0.1:<port>.
    nc -z 127.0.0.1 "$1" 2>/dev/null
}

# ── sidecars.env (sourced by health + down scripts) ───────────────────────────
cat > "${ENV_FILE}" <<'ENV'
# Auto-generated by sidecars-up.sh — do NOT edit by hand.
MINIO_PORT=9000
MINIO_ROOT_USER=snapdir-test
MINIO_ROOT_PASSWORD=snapdir-test-secret
MINIO_ADDR=127.0.0.1:9000
SSHD_PORT=2222
SSHD_USER=snapdir-parity
SSH_KEY=/workspace/scripts/sidecar_ssh_key
SSH_KNOWN_HOSTS=/workspace/scripts/sidecar_known_hosts
MINIO_DATA_DIR=/tmp/minio-data
MINIO_PID_FILE=/tmp/sidecars-minio.pid
SSHD_PID_FILE=/tmp/sidecars-sshd.pid
SSHD_HOST_KEY=/tmp/sidecar-sshd-host_key
SSHD_CONFIG=/tmp/sidecar-sshd.conf
SSHD_AUTH_KEYS=/tmp/sidecar-authorized_keys
ENV

# shellcheck source=/dev/null
. "${ENV_FILE}"

# ── 1. MinIO ──────────────────────────────────────────────────────────────────
if port_listening "${MINIO_PORT}"; then
    echo "sidecars-up: minio already listening on ${MINIO_PORT}, skipping"
else
    mkdir -p "${MINIO_DATA_DIR}"
    MINIO_ROOT_USER="${MINIO_ROOT_USER}" \
    MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD}" \
    minio server "${MINIO_DATA_DIR}" \
        --address "127.0.0.1:${MINIO_PORT}" \
        --quiet \
        > /tmp/sidecars-minio.log 2>&1 &
    echo "$!" > "${MINIO_PID_FILE}"
    echo "sidecars-up: minio started (pid $(cat "${MINIO_PID_FILE}")), port ${MINIO_PORT}"
fi

# ── 2. sshd ───────────────────────────────────────────────────────────────────
if port_listening "${SSHD_PORT}"; then
    echo "sidecars-up: sshd already listening on ${SSHD_PORT}, skipping"
else
    # Generate per-container host key (idempotent: reuse if present)
    if [ ! -f "${SSHD_HOST_KEY}" ]; then
        ssh-keygen -q -N "" -t ed25519 -f "${SSHD_HOST_KEY}"
    fi

    # Generate per-container client key (baked path; reuse if present)
    if [ ! -f "${SSH_KEY}" ]; then
        ssh-keygen -q -N "" -t ed25519 -f "${SSH_KEY}"
        chmod 600 "${SSH_KEY}"
    fi

    # authorized_keys for the current system user (sshd runs as same UID)
    cp "${SSH_KEY}.pub" "${SSHD_AUTH_KEYS}"
    chmod 600 "${SSHD_AUTH_KEYS}"

    # sshd requires /run/sshd for privilege separation (even with UsePrivilegeSeparation no).
    # When running as a non-root user, use sudo to create this root-owned directory.
    if [ "$(id -u)" = "0" ]; then
        mkdir -p /run/sshd
    else
        sudo mkdir -p /run/sshd
    fi

    # sshd_config — pubkey-only, no PAM, loopback, current user
    CURRENT_USER="$(id -un)"
    cat > "${SSHD_CONFIG}" <<SSHD_CONF
ListenAddress 127.0.0.1
Port ${SSHD_PORT}
HostKey ${SSHD_HOST_KEY}
AuthorizedKeysFile ${SSHD_AUTH_KEYS}
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
UsePAM no
StrictModes no
UsePrivilegeSeparation no
PidFile none
LogLevel ERROR
Subsystem sftp internal-sftp
AllowUsers ${CURRENT_USER}
SSHD_CONF

    # Start sshd in the foreground-daemon mode (-D keeps it alive;
    # -e writes log to stderr redirected to file).
    /usr/sbin/sshd -D -e -f "${SSHD_CONFIG}" \
        > /tmp/sidecars-sshd.log 2>&1 &
    echo "$!" > "${SSHD_PID_FILE}"
    echo "sidecars-up: sshd started (pid $(cat "${SSHD_PID_FILE}")), port ${SSHD_PORT}"

    # Build known_hosts so health/P36 can connect without prompts
    SSHD_HOST_PUB="$(cat "${SSHD_HOST_KEY}.pub" | awk '{print $1" "$2}')"
    printf '[127.0.0.1]:%s %s\n' "${SSHD_PORT}" "${SSHD_HOST_PUB}" \
        > "${SSH_KNOWN_HOSTS}"
fi

echo "sidecars-up: done"
