#ifndef SNAPDIR_H
#define SNAPDIR_H

/* Generated by cbindgen. DO NOT EDIT. */

#include <stdint.h>
#include <stdbool.h>

// The C ABI version for `snapdir-ffi`.
//
// Starts at `1` and is bumped ONLY on a breaking C-ABI change, decoupled
// from the crate semantic version.  cbindgen renders this as
// `#define SNAPDIR_ABI_VERSION 1` in `include/snapdir.h`.
#define SNAPDIR_ABI_VERSION 1

// Opaque error type returned by `snapdir-ffi` functions.
//
// The message and code strings are cached as `CString`s at construction time
// so that [`snapdir_error_message`] and [`snapdir_error_code`] can return
// stable `*const c_char` pointers that remain valid for the lifetime of the
// `SnapdirError` value.
//
// The caller **must not** free the pointers returned by the inspect functions;
// they borrow from `SnapdirError` itself. The caller **must** call
// [`snapdir_error_free`] exactly once when done with an error.
typedef struct SnapdirError SnapdirError;

// Returns the ancestor chain for `id` as a JSON array.
//
// `id` — 64-hex snapshot id.
// `catalog` — catalog name selector (currently unused; pass `NULL` for default).
// `err_out` — error out-parameter.
//
// Returns a freshly-allocated JSON string on success (caller frees with
// [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// JSON shape: `[{"created_at":"…","id":"…","location":"…"}, ...]`.
//
// # Safety
//
// `id` must be a valid NUL-terminated 64-hex C string. `catalog` may be `NULL`.
// `err_out` must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
char *snapdir_ancestors_json(const char *id, const char *_catalog, struct SnapdirError **err_out);

// Checks out a snapshot from the local cache into `dest_path`.
//
// The snapshot must have been fetched (via [`snapdir_fetch_blocking`] or
// [`snapdir_push_blocking`]) before this call.
//
// `id` — 64-hex snapshot id.
// `dest_path` — filesystem path to materialize into.
// `linked` — use symlinks instead of copies.
// `delete_extra` — delete destination files absent from the snapshot.
// `err_out` — error out-parameter.
//
// Returns `0` on success, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `id` and `dest_path` must be valid NUL-terminated UTF-8 C strings. `err_out`
// must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_checkout_blocking(const char *id,
                              const char *dest_path,
                              bool linked,
                              bool delete_extra,
                              struct SnapdirError **err_out);

// Diffs two sets of stores and returns a JSON array of change entries.
//
// `from_uris` — NULL-terminated array of source store URIs.
// `to_uris` — NULL-terminated array of destination store URIs.
// `id` — optional 64-hex snapshot id (passed to [`snapdir_api::DiffOptions`];
//         currently informational — the api unions all manifests per side).
//         For a self-diff pass the same store on both sides; the union will be
//         identical on each side, yielding an empty diff.
//         For an A→B diff across two distinct stores, pass `NULL`.
// `include_unchanged` — include unchanged entries in the output.
// `on_conflict` — conflict policy: `"error"` or `"last-wins"` (`NULL` = `"error"`).
// `err_out` — error out-parameter.
//
// Returns a freshly-allocated JSON string on success (caller frees with
// [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// JSON shape: `[{"status":"A","path":"./add.txt"}, ...]` where `status` is
// one of `"A"` (Added), `"D"` (Deleted), `"M"` (Modified), `"="` (Unchanged).
//
// # Safety
//
// `from_uris` and `to_uris` must be NULL-terminated arrays of valid NUL-terminated
// UTF-8 C string pointers (each inner pointer non-NULL). `id`, `on_conflict`, and
// `err_out` follow the same rules as other optional parameters.
char *snapdir_diff_json(const char **from_uris,
                        const char **to_uris,
                        const char *id,
                        bool include_unchanged,
                        const char *on_conflict,
                        struct SnapdirError **err_out);

// Returns the stable error code for `err`.
//
// The returned pointer is one of the 8 stable codes (`IO_ERROR`,
// `HASH_MISMATCH`, `STORE_ERROR`, `IN_FLUX`, `CATALOG_ERROR`, `INVALID_ID`,
// `INVALID_STORE`, `CONFLICT`) or `INTERNAL` for unexpected failures caught
// by the `catch_unwind` boundary.
//
// The returned pointer is valid for the lifetime of `err` — the caller must
// **NOT** free it separately.
//
// If `err` is `NULL`, returns `NULL`.
//
// # Safety
//
// `err` must be either `NULL` or a valid pointer to a `SnapdirError` that has
// not yet been freed.
const char *snapdir_error_code(const struct SnapdirError *err);

// Frees a `SnapdirError` previously returned via an error out-parameter.
//
// Passing `NULL` is a safe no-op.
//
// # Safety
//
// - `err` must be either `NULL` or a pointer previously written into an
//   `SnapdirError **err_out` out-parameter by a `snapdir-ffi` function.
// - `err` must not be freed more than once.
void snapdir_error_free(struct SnapdirError *err);

// Returns the human-readable error message for `err`.
//
// The returned pointer is valid for the lifetime of `err` — the caller must
// **NOT** free it separately. It is invalidated when `snapdir_error_free(err)`
// is called.
//
// If `err` is `NULL`, returns `NULL`.
//
// # Safety
//
// `err` must be either `NULL` or a valid pointer to a `SnapdirError` that has
// not yet been freed.
const char *snapdir_error_message(const struct SnapdirError *err);

// Fetches a snapshot from `store_uri` into the local cache.
//
// `id` — 64-hex snapshot id.
// `store_uri` — source store URI.
// `jobs` — max concurrent transfers (`0` = default).
// `err_out` — error out-parameter.
//
// Returns `0` on success, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `id` and `store_uri` must be valid NUL-terminated UTF-8 C strings. `err_out`
// must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_fetch_blocking(const char *id,
                           const char *store_uri,
                           uint32_t jobs,
                           struct SnapdirError **err_out);

// Flushes (empties) the local cache at `cache_dir`.
//
// `cache_dir` — the cache directory to flush (must not be `NULL`). A missing
// or empty cache directory is a successful no-op.
// `err_out` — error out-parameter.
//
// Returns `0` on success, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `cache_dir` must be a valid NUL-terminated UTF-8 C string. `err_out` must
// be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_flush_cache(const char *cache_dir, struct SnapdirError **err_out);

// Computes the snapshot id for the directory at `path`.
//
// `exclude` — an extended-regex exclusion pattern (`NULL` = no exclusion).
// `walk_jobs` — parallel hashing worker count (`0` = auto/CPU-count default).
// `cache_dir` — override the local object-cache directory (`NULL` = default).
// `err_out` — on failure, `*err_out` is set to a heap `SnapdirError`; the
// caller must free it with [`snapdir_error_free`]. On success, `*err_out`
// remains `NULL` and the returned string must be freed with
// [`snapdir_string_free`].
//
// Returns the 64-character lowercase hex BLAKE3 snapshot id on success, or
// `NULL` on failure (with `*err_out` set).
//
// # Safety
//
// `path` must be a valid, NUL-terminated UTF-8 C string. `exclude` and
// `cache_dir` may be `NULL`. `err_out` must be either `NULL` or a valid
// writable pointer to `*mut SnapdirError`.
char *snapdir_id(const char *path,
                 const char *exclude,
                 uint32_t walk_jobs,
                 const char *cache_dir,
                 struct SnapdirError **err_out);

// Computes the snapshot id from an already-computed manifest text string.
//
// The `manifest_text` must be a valid NUL-terminated UTF-8 string previously
// returned by [`snapdir_manifest`] (or equivalent). The returned id is the
// same 64-char lowercase-hex BLAKE3 id that [`snapdir_id`] would produce for
// the original directory.
//
// Returns a freshly-allocated id string on success (caller frees with
// [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// # Safety
//
// `manifest_text` must be a valid, NUL-terminated UTF-8 C string. `err_out`
// must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
char *snapdir_id_from_manifest_text(const char *manifest_text, struct SnapdirError **err_out);

// Initialises the embedded shared multi-thread tokio runtime.
//
// **Idempotent.** Safe to call many times and concurrently. Calling other
// `snapdir_*` functions before `snapdir_init` is also safe — they
// lazily initialise the runtime on first use — but calling `snapdir_init`
// explicitly at process startup allows bindings to front-load the
// initialisation cost.
//
// # Panics (C side)
//
// This function cannot fail visibly: if the runtime cannot be built (which
// should be extremely rare) the process will abort.
void snapdir_init(void);

// Returns all catalog locations as a JSON array.
//
// `cache_dir` — cache directory override (used for legacy reasons; catalog path
// is resolved from `$SNAPDIR_CATALOG_DB_PATH` or the default; `NULL` = default).
// `catalog` — catalog name selector (currently unused; pass `NULL` for default).
// `err_out` — error out-parameter.
//
// Returns a freshly-allocated JSON string on success (caller frees with
// [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// JSON shape: `[{"created_at":"…","id":"…","location":"…"}, ...]`.
//
// # Safety
//
// `cache_dir` and `catalog` may be `NULL`. `err_out` must be either `NULL` or
// a valid writable pointer to `*mut SnapdirError`.
char *snapdir_locations_json(const char *_cache_dir,
                             const char *_catalog,
                             struct SnapdirError **err_out);

// Walks `path` and returns the manifest text as an owned C string.
//
// `exclude` — an extended-regex exclusion pattern (`NULL` = no exclusion).
// `walk_jobs` — parallel hashing worker count (`0` = auto/CPU-count default).
// `absolute` — emit absolute paths instead of `./`-relative paths.
// `no_follow` — do not follow symbolic links.
// `checksum_bin` — checksum algorithm (`NULL` = `"b3sum"` default; `"md5sum"`
// or `"sha256sum"` selects that algorithm).
// `cache_dir` — override the local object-cache directory (`NULL` = default).
// `catalog` — catalog adapter selection (`NULL` = adapter default;
// `"none"` = suppress catalog recording; any other string = named adapter).
// `err_out` — on failure, `*err_out` is set to a heap `SnapdirError`; the
// caller must free it with [`snapdir_error_free`]. On success, `*err_out`
// remains `NULL` and the returned string must be freed with
// [`snapdir_string_free`].
//
// Returns the manifest text on success, or `NULL` on failure (with `*err_out`
// set).
//
// # Safety
//
// `path` must be a valid, NUL-terminated UTF-8 C string. `exclude`,
// `checksum_bin`, `cache_dir`, and `catalog` may be `NULL`. `err_out` must
// be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
char *snapdir_manifest(const char *path,
                       const char *exclude,
                       uint32_t walk_jobs,
                       bool absolute,
                       bool no_follow,
                       const char *checksum_bin,
                       const char *cache_dir,
                       const char *catalog,
                       struct SnapdirError **err_out);

// Pulls a snapshot from `store_uri` into `dest_path`, materializing its files.
//
// `id` — 64-hex snapshot id.
// `store_uri` — source store URI.
// `dest_path` — filesystem path to materialize into.
// `delete_extra` — if `true`, delete destination files absent from the snapshot.
// `jobs` — max concurrent transfers (`0` = default).
// `err_out` — error out-parameter.
//
// Returns `0` on success, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `id`, `store_uri`, and `dest_path` must be valid NUL-terminated UTF-8 C strings.
// `err_out` must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_pull_blocking(const char *id,
                          const char *store_uri,
                          const char *dest_path,
                          bool delete_extra,
                          uint32_t jobs,
                          struct SnapdirError **err_out);

// Pushes the snapshot at `source_path` (or by `source_id` if already staged)
// to `store_uri` and returns the snapshot id string.
//
// `source_path` — filesystem path to the directory to push (XOR with `source_id`).
// `source_id` — 64-hex id of a previously-staged snapshot (`NULL` when using path).
// `store_uri` — destination store URI (e.g. `"file:///tmp/store"`).
// `jobs` — max concurrent transfers (`0` = default).
// `limit_rate` — bandwidth cap string (e.g. `"10M"`; `NULL` = unlimited).
// `max_retries` — max retry attempts per object (`0` = default of 5).
// `cache_dir` — local cache directory override (`NULL` = default).
// `err_out` — error out-parameter.
//
// Returns the 64-char lowercase hex snapshot id on success, or `NULL` on failure.
//
// # Safety
//
// `store_uri` and (if non-NULL) `source_path`/`source_id` must be valid NUL-terminated
// UTF-8 C strings. `err_out` must be either `NULL` or a valid writable pointer.
char *snapdir_push_blocking(const char *source_path,
                            const char *source_id,
                            const char *store_uri,
                            uint32_t jobs,
                            const char *limit_rate,
                            uint32_t max_retries,
                            const char *cache_dir,
                            struct SnapdirError **err_out);

// Returns the revision history at `location` as a JSON array.
//
// `location` — store URI or catalog location path to look up.
// `catalog` — catalog name selector (currently unused; pass `NULL` for default).
// `err_out` — error out-parameter.
//
// Returns a freshly-allocated JSON string on success (caller frees with
// [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// JSON shape: `[{"created_at":"…","id":"…","previous_id":null_or_"…"}, ...]`.
//
// # Safety
//
// `location` must be a valid NUL-terminated UTF-8 C string. `catalog` may be
// `NULL`. `err_out` must be either `NULL` or a valid writable pointer to
// `*mut SnapdirError`.
char *snapdir_revisions_json(const char *location,
                             const char *_catalog,
                             struct SnapdirError **err_out);

// Stages the directory at `path` in the local cache and returns the snapshot id.
//
// `keep` — if `true`, the source tree is preserved as-is after staging
// (the snapshot objects are written to `cache_dir`); if `false`, only the
// cache copy is kept (source tree unchanged — the option mainly controls
// CLI behavior; the FFI always leaves the source directory intact).
// `cache_dir` — override the local cache directory (`NULL` = default).
//
// Returns the 64-char lowercase hex snapshot id on success (caller frees
// with [`snapdir_string_free`]), or `NULL` on failure (with `*err_out` set).
//
// # Safety
//
// `path` must be a valid, NUL-terminated UTF-8 C string. `cache_dir` may be
// `NULL`. `err_out` must be either `NULL` or a valid writable pointer to
// `*mut SnapdirError`.
char *snapdir_stage(const char *path,
                    bool keep,
                    const char *cache_dir,
                    struct SnapdirError **err_out);

// Frees a string previously returned by a `snapdir_*` function.
//
// The string must have been allocated by a `snapdir-ffi` function via
// `CString::into_raw`. Passing `NULL` is a safe no-op.
//
// # Safety
//
// - `s` must be either `NULL` or a pointer previously returned by a
//   `snapdir-ffi` function that returns an owned `char *`.
// - `s` must not be freed more than once.
void snapdir_string_free(char *s);

// Syncs a snapshot from `src_uri` to `dst_uri`.
//
// `id` — 64-hex snapshot id.
// `src_uri` — source store URI.
// `dst_uri` — destination store URI.
// `jobs` — max concurrent transfers (`0` = default).
// `err_out` — error out-parameter.
//
// Returns `0` on success, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `id`, `src_uri`, and `dst_uri` must be valid NUL-terminated UTF-8 C strings.
// `err_out` must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_sync_blocking(const char *id,
                          const char *src_uri,
                          const char *dst_uri,
                          uint32_t jobs,
                          struct SnapdirError **err_out);

// Verifies a snapshot in `store_uri` — checks that all objects are present
// and hash-consistent.
//
// `id` — 64-hex snapshot id.
// `store_uri` — store URI to verify against.
// `purge` — remove corrupt objects from the local cache during verification.
// `err_out` — error out-parameter.
//
// Returns `0` if the snapshot is healthy, `-1` on failure (with `*err_out` set).
//
// # Safety
//
// `id` and `store_uri` must be valid NUL-terminated UTF-8 C strings. `err_out`
// must be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_verify_blocking(const char *id,
                            const char *store_uri,
                            bool purge,
                            struct SnapdirError **err_out);

// Verifies the local cache at `cache_dir`.
//
// `cache_dir` — the cache directory to verify (must not be `NULL`).
// `purge` — if `true`, remove corrupt objects from the cache (currently
//            passed through to `snapdir_api::verify_cache`; the `purge`
//            semantics are handled by the api layer).
// `err_out` — error out-parameter.
//
// Returns `0` if the cache is clean (or empty), `-1` on failure (with
// `*err_out` set).
//
// # Safety
//
// `cache_dir` must be a valid NUL-terminated UTF-8 C string. `err_out` must
// be either `NULL` or a valid writable pointer to `*mut SnapdirError`.
int snapdir_verify_cache(const char *cache_dir, bool _purge, struct SnapdirError **err_out);

// Returns the snapdir version string (e.g. `"1.10.0"`).
//
// The returned pointer has **static lifetime** — the caller **must NOT free
// it**. It remains valid for the entire process lifetime.
const char *snapdir_version(void);

#endif  /* SNAPDIR_H */
